# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sai < Formula
  desc "CLI tool for the SAI Platform - ArenaX Labs"
  homepage "https://competesai.com"
  version "0.0.14"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://storage.googleapis.com/axl-binaries/sai/v0.0.14/sai_0.0.14_darwin_amd64.tar.gz"
      sha256 "c982dc0d46c1526d2ba76d5f60266ced790ca79473e97767888cb8f1b36da187"

      def install
        bin.install "sai"
      end
    end
    if Hardware::CPU.arm?
      url "https://storage.googleapis.com/axl-binaries/sai/v0.0.14/sai_0.0.14_darwin_arm64.tar.gz"
      sha256 "6dd2cac316d1f6fb732b524771dfa66af1c74fadfa344fe354be97b520bcc05b"

      def install
        bin.install "sai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://storage.googleapis.com/axl-binaries/sai/v0.0.14/sai_0.0.14_linux_amd64.tar.gz"
        sha256 "92d7afb86708fb35d10d49e08b8cd75f73b02947794831835ed82c10caea9ba1"

        def install
          bin.install "sai"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://storage.googleapis.com/axl-binaries/sai/v0.0.14/sai_0.0.14_linux_arm64.tar.gz"
        sha256 "edc0e0ec0f10be5db2150f6a5c53474ca90f753e773bad34aa6fddcc88470cc6"

        def install
          bin.install "sai"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Before using this software, you MUST authenticate with your API token:

          $ sai login --token YOUR_API_TOKEN

      You can obtain a token from your account settings.
      Without a valid token, this CLI will not function.
    EOS
  end
end
