# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sai < Formula
  desc "CLI tool for the SAI Platform - ArenaX Labs"
  homepage "https://competesai.com"
  version "0.0.15"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://storage.googleapis.com/axl-binaries/sai/v0.0.15/sai_0.0.15_darwin_amd64.tar.gz"
      sha256 "82c7ff856ef99758c1e7e74cc36a2d70f908b9395fb8f91f94737ee43dce6921"

      def install
        bin.install "sai"
      end
    end
    if Hardware::CPU.arm?
      url "https://storage.googleapis.com/axl-binaries/sai/v0.0.15/sai_0.0.15_darwin_arm64.tar.gz"
      sha256 "7aa6b2bce4b5f00f19d926727121b2010b68462702add13165ebc832960255a8"

      def install
        bin.install "sai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://storage.googleapis.com/axl-binaries/sai/v0.0.15/sai_0.0.15_linux_amd64.tar.gz"
        sha256 "6f8273be396dd3ef6a93661372982c10bbe9930fa985d006b04d198db82f1710"

        def install
          bin.install "sai"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://storage.googleapis.com/axl-binaries/sai/v0.0.15/sai_0.0.15_linux_arm64.tar.gz"
        sha256 "dc46504baf3d520dce07af6aa0e8e07c31cc7b58b4ecd28c9c3b47125519ca88"

        def install
          bin.install "sai"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Before using this software, you MUST authenticate with your API token:

          $ sai login --token YOUR_API_TOKEN

      You can obtain a token from your account settings.
      Without a valid token, this CLI will not function.
    EOS
  end
end
